// Shared loader for the duplicate drop-list (data/derived/duplicate-drops.tsv,
// generated by pipeline/dedupe.js). Returns a Set of citation ids that
// downstream consumers (build_gold.js, membership_matrix.js, the profile
// scripts) should skip. The drop-list spans all emonyms and cryptoclasses;
// callers just test membership, so ids outside their scope are harmless.
//
// See notes/gold-cleanup-status.md (Problem 2) for how this is applied.

const fs = require('fs');
const path = require('path');

function loadDropIds(repo = path.resolve(__dirname, '..')) {
  const file = path.join(repo, 'data', 'derived', 'duplicate-drops.tsv');
  if (!fs.existsSync(file)) return new Set();
  const lines = fs.readFileSync(file, 'utf8').split(/\r?\n/).filter(Boolean);
  lines.shift(); // header: drop_id\tkeep_id\t...
  return new Set(lines.map(l => l.split('\t')[0]).filter(Boolean));
}

module.exports = { loadDropIds };
