#!/usr/bin/env node
// Render the canonical 3-index tables (data/derived/cryptoclass-indices.md) as a
// Word-compatible HTML file. Word opens .html directly and preserves table
// formatting. This is a pure presentation layer: every number comes verbatim
// from cryptoclass-indices.md (itself generated by pipeline/compute_indices.js),
// so the export can never drift from the source of truth.
//
// Usage:  node pipeline/export_tables_html.js
// Output: data/derived/autoreferat-tables.html

const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..');
const SRC = path.join(REPO, 'data', 'derived', 'cryptoclass-indices.md');
const OUT = path.join(REPO, 'data', 'derived', 'autoreferat-tables.html');

const md = fs.readFileSync(SRC, 'utf8').split(/\r?\n/);

// Russian captions for the source sections (keyed on the raw "## " heading text).
const CAPTION = {
  'M — final classifier inventory': 'M — инвентарь классификаторов (по классам)',
  'Sᵢ — corpus frequency': 'Sᵢ — корпусная частота (словоупотребления)',
  'ПоКА — % of total frequency': 'ПоКА (%) — доля корпусной частоты',
  'ИРа = Qᵢ/M — breadth': 'ИРа = Qᵢ/M — разнообразие сочетаемости (широта)',
  'Qᵢ — distinct classifiers realized': 'Qᵢ — число реализованных классификаторов',
  'Доля ведущего классификатора (%) — concentration summary of СИ, not СИ itself': 'Доля ведущего классификатора (%) — концентрация (сводка СИ)',
  'Membership (symbol + ПоКА %)': 'Криптоклассная принадлежность (символ + ПоКА %)',
};

// ---- Parse: walk lines, grouping consecutive "|" rows into tables, captioned
// by the most recent "## " heading. The bulleted "Lead classifier" section is
// not a table and is skipped.
const tables = [];
let heading = null;
for (let i = 0; i < md.length; i++) {
  const line = md[i];
  const h = line.match(/^##\s+(.*)$/);
  if (h) { heading = h[1].trim(); continue; }
  if (line.trim().startsWith('|')) {
    const rows = [];
    while (i < md.length && md[i].trim().startsWith('|')) { rows.push(md[i]); i++; }
    i--;
    // rows[0] = header, rows[1] = |---| separator, rest = body
    const cells = r => r.trim().replace(/^\|/, '').replace(/\|$/, '').split('|').map(c => c.trim());
    const header = cells(rows[0]);
    const body = rows.slice(2).map(cells);
    if (CAPTION[heading]) tables.push({ caption: CAPTION[heading], header, body });
  }
}

// ---- minimal markdown -> HTML for cell content (*italic*, **bold**)
const esc = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const mdInline = s => esc(s)
  .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
  .replace(/\*(.+?)\*/g, '<em>$1</em>');

// ---- styles (Arial, Word-friendly)
const tableStyle = 'border-collapse:collapse;margin-bottom:18pt;';
const cS = 'border:1px solid #999;padding:4px 8px;text-align:center;font-family:Arial,sans-serif;font-size:10pt;';
const hS = 'border:1px solid #999;padding:4px 8px;text-align:center;font-family:Arial,sans-serif;font-size:10pt;background:#d9d9d9;font-weight:bold;';
const fS = 'border:1px solid #999;padding:4px 8px;text-align:left;font-family:Arial,sans-serif;font-size:10pt;'; // first column (emonym / class)

function renderTable(t, idx) {
  const out = [];
  // Left-align the first column only when it is a row label (the «эмоним» column),
  // not when the table is a single numeric row (the M inventory).
  const labelFirst = /emonym|эмоним/i.test(t.header[0]);
  out.push(`<h3 style="font-family:Arial,sans-serif;">Таблица ${idx}. ${t.caption}</h3>`);
  out.push(`<table style="${tableStyle}"><tr>`);
  t.header.forEach(c => out.push(`<th style="${hS}">${mdInline(c)}</th>`));
  out.push('</tr>');
  for (const row of t.body) {
    out.push('<tr>');
    row.forEach((c, j) => out.push(`<td style="${j === 0 && labelFirst ? fS : cS}">${mdInline(c)}</td>`));
    out.push('</tr>');
  }
  out.push('</table>');
  return out.join('\n');
}

const parts = [];
parts.push(`<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<title>Таблицы автореферата — криптоклассная принадлежность испанских эмонимов</title>
</head><body style="font-family:Arial,sans-serif;font-size:10pt;margin:36pt;">
<p style="font-size:9pt;color:#555;">Сформировано: ${new Date().toISOString().slice(0, 10)} &nbsp;|&nbsp;
Источник (источник истины для чисел): <code>data/derived/cryptoclass-indices.md</code> &nbsp;|&nbsp;
единица подсчёта: <strong>словоупотребление</strong> (Σ корпусной частоты).</p>
<p style="font-size:9pt;color:#555;">Три показателя читаются совместно: <strong>ПоКА</strong> — глубина (доля частоты класса),
<strong>ИРа</strong> — разнообразие сочетаемости (Qᵢ/M), <strong>СИ</strong> — сочетательная избирательность (профиль сочетаемости), концентрация которой измеряется <strong>долей ведущего классификатора</strong>.
Развёрнутое описание, интерпретация и примеры — в <code>data/derived/autoreferat-prose-3index-ru.md</code>.</p>
<p style="font-size:9pt;color:#555;">Условные обозначения принадлежности (приоритет ▲ → ★ → ○ → + → ~ → ·):
<strong>▲</strong> частотно-доминантный, но сосредоточенный на одном классификаторе (ПоКА ≥ 10 %, доля ведущего классификатора ≥ 80 %);
<strong>★</strong> ядерный (ПоКА ≥ 10 %, доля ведущего классификатора &lt; 80 %, ≥ 3 классификаторов);
<strong>○</strong> широкий по сочетаемости, но малочастотный (ПоКА &lt; 10 %, ИРа ≥ 0,50, доля ведущего классификатора ≤ 60 %);
<strong>+</strong> периферийный; <strong>~</strong> маргинальный; <strong>·</strong> не входит.
Обороты с опорным глаголом (<em>coger miedo</em>, <em>traer alegría</em>, <em>desatar la ira</em>) считаются
<strong>диагностирующими</strong> членство; их сосредоточенность фиксируется долей ведущего классификатора.</p>`);

tables.forEach((t, k) => parts.push(renderTable(t, k + 1)));

parts.push('</body></html>');

fs.writeFileSync(OUT, parts.join('\n'), 'utf8');
console.log(`Записано: ${OUT} (${tables.length} таблиц из cryptoclass-indices.md)`);
console.log('Откройте файл в Word (Файл > Открыть) — таблицы импортируются с сохранением форматирования.');
