#!/usr/bin/env node
// Build data/derived/freq-audit-parvae.md — a per-cell validation report for
// the frequency-aware re-extraction of Res Parvae (extract_wide.js). Lets a
// human verify every derived corpus frequency against the source xlsx before
// the corrected citations.tsv is trusted downstream.
//
// Reads the committed data/citations.tsv (so the report reflects exactly what
// the pipeline produced). Usage: node pipeline/freq_audit_parvae.js

const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..');

// Which cryptoclass to audit (default Res Parvae). Usage:
//   node pipeline/freq_audit_parvae.js ["Res Liquidae"]
const CLASS = process.argv.slice(2).join(' ').trim() || 'Res Parvae';
const SLUG = { 'Res Parvae': 'parvae', 'Res Acutae': 'acutae', 'Res Liquidae': 'liquidae',
  'Res Filiformes': 'filiformes', 'Res Continens': 'continens' }[CLASS]
  || CLASS.toLowerCase().replace(/[^a-z]+/g, '-').replace(/^-|-$/g, '');
const OUT = path.join(REPO, 'data', 'derived', `freq-audit-${SLUG}.md`);

// Baseline (pre-frequency) row counts, for the before/after table (Parvae only).
const BASELINE_BY_CLASS = { 'Res Parvae': { miedo: 34, amor: 82, ira: 10, tristeza: 3, 'alegría': 41 } };
const BASELINE = BASELINE_BY_CLASS[CLASS] || null;
const EMONYMS = ['miedo', 'tristeza', 'amor', 'alegría', 'ira'];

const tsv = fs.readFileSync(path.join(REPO, 'data', 'citations.tsv'), 'utf8');
const lines = tsv.split(/\r?\n/).filter(Boolean);
const h = lines.shift().split('\t');
const ix = Object.fromEntries(h.map((c, i) => [c, i]));

const rows = [];
for (const ln of lines) {
  const c = ln.split('\t');
  if (c[ix.cryptoclass] !== CLASS) continue;
  rows.push({
    emonym: c[ix.emonym], country: c[ix.country], ct: c[ix.construction_type],
    lemma: c[ix.classifier_lemma], cit: c[ix.citation_es],
    loc: c[ix.source_locator], note: c[ix.notes],
    freq: parseInt(c[ix.frequency], 10) || 0, role: c[ix.freq_role],
  });
}

const sum = (arr, f) => arr.reduce((a, r) => a + f(r), 0);
const out = [];
const P = s => out.push(s);

P(`# ${CLASS} — frequency re-extraction audit`);
P('');
P('Generated by `pipeline/freq_audit_parvae.js` from `data/citations.tsv`.');
P('Validates the frequency-aware parsing in `pipeline/extract_wide.js`');
P('(see `data/SCHEMA.md` → "Frequency formats"). Each block\'s corpus frequency is');
P('resolved by precedence: `Total: N` > inline `<classifier> N` > count of');
P('examples; a leading `1` opening a `1,2,3…` run is example-numbering; a summary');
P('label after its examples (Format 4) summarises them (no double count).');
P('');
P('`freq_role`: `inline` / `total` (authoritative count) · `example` (one quoted');
P('occurrence, weight 1) · `illustrative` (sample under an explicit count, weight');
P('0) · `absent` (searched, 0 hits, weight 0).');
P('');

// ---- totals ----
P('## Totals (Σ frequency) per emonym');
P('');
if (BASELINE) {
  P('| emonym | previous rows | corrected Σfreq | rows now | absent(0) cells |');
  P('|---|--:|--:|--:|--:|');
} else {
  P('| emonym | Σfreq | rows | absent(0) cells |');
  P('|---|--:|--:|--:|');
}
for (const e of EMONYMS) {
  const er = rows.filter(r => r.emonym === e);
  const sumf = sum(er, r => r.freq);
  const absent = er.filter(r => r.role === 'absent').length;
  if (BASELINE) P(`| ${e} | ${BASELINE[e]} | **${sumf}** | ${er.length} | ${absent} |`);
  else P(`| ${e} | **${sumf}** | ${er.length} | ${absent} |`);
}
P('');
P(`Distribution of \`freq_role\` across all ${CLASS} rows:`);
const roleCounts = {};
for (const r of rows) roleCounts[r.role] = (roleCounts[r.role] || 0) + 1;
P('');
P('| role | rows | meaning |');
P('|---|--:|---|');
const roleMeaning = {
  inline: 'authoritative count from `<classifier> N`',
  total: 'authoritative count from a `Total: N` line',
  example: 'one quoted occurrence (weight 1)',
  illustrative: 'sample sentence under an explicit total (weight 0)',
  absent: 'construction searched, 0 occurrences (weight 0)',
};
for (const k of ['inline', 'total', 'example', 'illustrative', 'absent']) {
  if (roleCounts[k]) P(`| ${k} | ${roleCounts[k]} | ${roleMeaning[k]} |`);
}
P('');

// ---- Weighted lemma breakdown ----
P('## Weighted classifier breakdown per emonym (Σfreq, freq>0)');
P('');
for (const e of EMONYMS) {
  const er = rows.filter(r => r.emonym === e && r.freq > 0);
  const byL = {};
  for (const r of er) byL[r.lemma || '(blank)'] = (byL[r.lemma || '(blank)'] || 0) + r.freq;
  const top = Object.entries(byL).sort((a, b) => b[1] - a[1]);
  const tot = sum(er, r => r.freq);
  const lead = top[0] ? `${top[0][0]} ${(100 * top[0][1] / tot).toFixed(0)}%` : '—';
  P(`- **${e}** (Σ=${tot}; lead ${lead}): ` + top.map(([k, v]) => `${k} ${v}`).join(', '));
}
P('');
P('> The lead-classifier share drives the membership verdict: a lead share ≥ 90 %');
P('> trips the idiom guard (marginal `~`) — the emonym attaches to the class');
P('> through essentially one construction.');
P('');

// ---- FLAGS ----
P('## ⚠ Cells needing a human decision');
P('');
const flags = rows.filter(r => /FLAG/.test(r.note));
if (!flags.length) P('_None._');
else {
  P('| locator | emonym/country | lemma | freq | note | citation |');
  P('|---|---|---|--:|---|---|');
  for (const r of flags) {
    P(`| ${r.loc} | ${r.emonym}/${r.country} | ${r.lemma} | ${r.freq} | ${r.note} | ${r.cit.slice(0, 50)} |`);
  }
}
P('');

// ---- Full per-cell appendix ----
P('## Appendix — full per-cell parse');
P('');
P(`Every ${CLASS} row, grouped emonym → country. \`freq\` is the contribution to`);
P('Σ; `·` marks weight-0 rows (illustrative / absent). Verify against the xlsx');
P('cell at the given locator.');
P('');
for (const e of EMONYMS) {
  P(`### ${e}`);
  P('');
  const er = rows.filter(r => r.emonym === e);
  const countries = [...new Set(er.map(r => r.country))];
  for (const co of countries) {
    const cr = er.filter(r => r.country === co);
    const csum = sum(cr, r => r.freq);
    P(`**${co}** (Σ=${csum})`);
    P('');
    for (const r of cr) {
      const w = r.freq > 0 ? String(r.freq).padStart(4) : '   ·';
      const cit = (r.cit || '').replace(/\|/g, '\\|').slice(0, 80);
      P(`- \`${w}\` ${r.role.padEnd(12)} ${(r.lemma || '—').padEnd(12)} [${r.loc}] ${cit}`);
    }
    P('');
  }
}

fs.writeFileSync(OUT, out.join('\n') + '\n', 'utf8');
process.stderr.write(`Wrote ${path.relative(REPO, OUT)} (${rows.length} ${CLASS} rows)\n`);
