#!/usr/bin/env node
// Build data/derived/freq-audit-parvae.md — a per-cell validation report for
// the frequency-aware re-extraction of Res Parvae (extract_wide.js). Lets a
// human verify every derived corpus frequency against the source xlsx before
// the corrected citations.tsv is trusted downstream.
//
// Reads the committed data/citations.tsv (so the report reflects exactly what
// the pipeline produced). Usage: node pipeline/freq_audit_parvae.js

const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..');
const OUT = path.join(REPO, 'data', 'derived', 'freq-audit-parvae.md');

// Baseline (pre-frequency) Res Parvae row counts, for the before/after table.
const BASELINE = { miedo: 34, amor: 82, ira: 10, tristeza: 3, 'alegría': 41 };
const EMONYMS = ['miedo', 'tristeza', 'amor', 'alegría', 'ira'];

const tsv = fs.readFileSync(path.join(REPO, 'data', 'citations.tsv'), 'utf8');
const lines = tsv.split(/\r?\n/).filter(Boolean);
const h = lines.shift().split('\t');
const ix = Object.fromEntries(h.map((c, i) => [c, i]));

const rows = [];
for (const ln of lines) {
  const c = ln.split('\t');
  if (c[ix.cryptoclass] !== 'Res Parvae') continue;
  rows.push({
    emonym: c[ix.emonym], country: c[ix.country], ct: c[ix.construction_type],
    lemma: c[ix.classifier_lemma], cit: c[ix.citation_es],
    loc: c[ix.source_locator], note: c[ix.notes],
    freq: parseInt(c[ix.frequency], 10) || 0, role: c[ix.freq_role],
  });
}

const sum = (arr, f) => arr.reduce((a, r) => a + f(r), 0);
const out = [];
const P = s => out.push(s);

P('# Res Parvae — frequency re-extraction audit');
P('');
P('Generated by `pipeline/freq_audit_parvae.js` from `data/citations.tsv`.');
P('Validates the frequency-aware parsing added to `pipeline/extract_wide.js`');
P('(gated to `Res Parvae.xlsx`; see `data/SCHEMA.md` → "Frequency formats").');
P('');
P('**What changed.** The legacy extractor kept only the example *sentences* in a');
P('cell and discarded every explicit corpus count (`coger miedo 199`, `Total 29`,');
P('`SOLTAR 0`). Res Parvae therefore reduced to 170 example rows with no');
P('productivity signal. The new parser segments each cell into classifier blocks');
P('and assigns a corpus **frequency** per block, by this precedence:');
P('');
P('1. `Total: N` line  → authoritative N; shown examples become `illustrative` (weight 0).');
P('2. inline `<classifier> <emonym> N`  → frequency N (`inline`); a `0` is `absent` (searched, not found).');
P('3. examples only (no number)  → frequency = count of examples (each weight 1).');
P('4. a leading `1` opening a `1,2,3…` run is example-numbering, not a frequency.');
P('');
P('Two new `citations.tsv` columns carry this: `frequency` (int) and `freq_role`');
P('(`inline` / `total` / `example` / `illustrative` / `absent`). All non-Parvae');
P('classes keep `frequency = 1`, so their numbers are unchanged.');
P('');

// ---- Before/after totals ----
P('## Corrected totals (Σ frequency) vs. previous extraction');
P('');
P('| emonym | previous rows | corrected Σfreq | rows now | absent(0) cells |');
P('|---|--:|--:|--:|--:|');
for (const e of EMONYMS) {
  const er = rows.filter(r => r.emonym === e);
  const sumf = sum(er, r => r.freq);
  const absent = er.filter(r => r.role === 'absent').length;
  P(`| ${e} | ${BASELINE[e]} | **${sumf}** | ${er.length} | ${absent} |`);
}
P('');
P('Distribution of `freq_role` across all Res Parvae rows:');
const roleCounts = {};
for (const r of rows) roleCounts[r.role] = (roleCounts[r.role] || 0) + 1;
P('');
P('| role | rows | meaning |');
P('|---|--:|---|');
const roleMeaning = {
  inline: 'authoritative count from `<classifier> N`',
  total: 'authoritative count from a `Total: N` line',
  example: 'one quoted occurrence (weight 1)',
  illustrative: 'sample sentence under an explicit total (weight 0)',
  absent: 'construction searched, 0 occurrences (weight 0)',
};
for (const k of ['inline', 'total', 'example', 'illustrative', 'absent']) {
  if (roleCounts[k]) P(`| ${k} | ${roleCounts[k]} | ${roleMeaning[k]} |`);
}
P('');

// ---- Weighted lemma breakdown ----
P('## Weighted classifier breakdown per emonym (Σfreq, freq>0)');
P('');
for (const e of EMONYMS) {
  const er = rows.filter(r => r.emonym === e && r.freq > 0);
  const byL = {};
  for (const r of er) byL[r.lemma || '(blank)'] = (byL[r.lemma || '(blank)'] || 0) + r.freq;
  const top = Object.entries(byL).sort((a, b) => b[1] - a[1]);
  const tot = sum(er, r => r.freq);
  const lead = top[0] ? `${top[0][0]} ${(100 * top[0][1] / tot).toFixed(0)}%` : '—';
  P(`- **${e}** (Σ=${tot}; lead ${lead}): ` + top.map(([k, v]) => `${k} ${v}`).join(', '));
}
P('');
P('> The single-classifier dominance above drives the membership verdicts: a lead');
P('> share ≥ 90 % trips the idiom guard (marginal `~`). miedo (`coger` 90.1 %) and');
P('> tristeza (`traer` 92 %) are marginal for exactly this reason — they attach to');
P('> Res Parvae through essentially one construction.');
P('');

// ---- FLAGS ----
P('## ⚠ Cells needing a human decision');
P('');
const flags = rows.filter(r => /FLAG/.test(r.note));
if (!flags.length) P('_None._');
else {
  P('| locator | emonym/country | lemma | freq | note | citation |');
  P('|---|---|---|--:|---|---|');
  for (const r of flags) {
    P(`| ${r.loc} | ${r.emonym}/${r.country} | ${r.lemma} | ${r.freq} | ${r.note} | ${r.cit.slice(0, 50)} |`);
  }
}
P('');

// ---- Full per-cell appendix ----
P('## Appendix — full per-cell parse');
P('');
P('Every Res Parvae row, grouped emonym → country. `freq` is the contribution to');
P('Σ; `·` marks weight-0 rows (illustrative / absent). Verify against the xlsx');
P('cell at the given locator.');
P('');
for (const e of EMONYMS) {
  P(`### ${e}`);
  P('');
  const er = rows.filter(r => r.emonym === e);
  const countries = [...new Set(er.map(r => r.country))];
  for (const co of countries) {
    const cr = er.filter(r => r.country === co);
    const csum = sum(cr, r => r.freq);
    P(`**${co}** (Σ=${csum})`);
    P('');
    for (const r of cr) {
      const w = r.freq > 0 ? String(r.freq).padStart(4) : '   ·';
      const cit = (r.cit || '').replace(/\|/g, '\\|').slice(0, 80);
      P(`- \`${w}\` ${r.role.padEnd(12)} ${(r.lemma || '—').padEnd(12)} [${r.loc}] ${cit}`);
    }
    P('');
  }
}

fs.writeFileSync(OUT, out.join('\n') + '\n', 'utf8');
process.stderr.write(`Wrote ${path.relative(REPO, OUT)} (${rows.length} Res Parvae rows)\n`);
